### ISSUE TITLE
Delete Google OAuth stuff

### ISSUE THREAD

**Issue by thunderingluck** [CFG-Allston-Brighton/website#2]
Remove api calls etc

**Comment by jennet-zamanova** [comment]
so we would not check whether the user opened two different windows in the browser (we are not trying to keep both windows the same)?

**Comment by thunderingluck** [comment]
i don’t think that would be necessary? what are your thoughts?

**Comment by jennet-zamanova** [comment]
yeah, that makes sense. I made a pr if you could take a look
